language: python
python:
  - "3.6"
# command to install dependencies

dist: trusty
sudo: false

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
# command to run tests
script:
  coverage run test_bench.py
after_success:
  coveralls
