language: python
python:
  - "3.6"

dist: trusty
sudo: false

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
# command to run tests
script:
  coverage run factorizer/test_bench.py
after_success:
  coveralls

notifications:
  email: false
#    recipients:
#      - one@example.com
#      - other@example.com
#    on_success: never # default: change
#    on_failure: always # default: always