version:  '2'
services:
  tfserver1:
    image: "tensorflow/tensorflow:latest-py3"
    command:
      python3 /code/async.py --ps_hosts=tfserver1:4444,tfserver2:4444 --worker_hosts=tfworker1:4444,tfworker2:4445,tfworker3:4556 --job_name=ps --task_index=0
    volumes:
      - .:/code

  tfserver2:
    image: "tensorflow/tensorflow:latest-py3"
    command:
      python3 /code/async.py --ps_hosts=tfserver1:4444,tfserver2:4444  --worker_hosts=tfworker1:4444,tfworker2:4445,tfworker3:4556 --job_name=ps --task_index=1
    volumes:
      - .:/code

  tfworker1:
    image: "tensorflow/tensorflow:latest-py3"
    command:
      python3 /code/async.py --ps_hosts=tfserver1:4444,tfserver2:4444  --worker_hosts=tfworker1:4444,tfworker2:4445,tfworker3:4556 --job_name=worker --task_index=0
    volumes:
      - .:/code
    links:
      - tfserver1
      - tfserver2

  tfworker2:
    image: "tensorflow/tensorflow:latest-py3"
    command:
      python3 /code/async.py --ps_hosts=tfserver1:4444,tfserver2:4444  --worker_hosts=tfworker1:4444,tfworker2:4445,tfworker3:4556 --job_name=worker --task_index=1
    volumes:
      - .:/code
    links:
      - tfserver1
      - tfserver2

  tfworker3:
    image: "tensorflow/tensorflow:latest-py3"
    command:
      python3 /code/async.py --ps_hosts=tfserver1:4444,tfserver2:4444  --worker_hosts=tfworker1:4444,tfworker2:4445,tfworker3:4556 --job_name=worker --task_index=2
    volumes:
      - .:/code
    links:
      - tfserver1
      - tfserver2